"""Third migration

Revision ID: 0adb98f1222f
Revises: af71521533b5
Create Date: 2023-06-15 21:24:19.501896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adb98f1222f'
down_revision = 'af71521533b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id', 'barcode'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cart_product',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('cart_id', 'product_id')
    )
    op.drop_table('products')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Total',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=False))
        batch_op.alter_column('Total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=12), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id', 'barcode'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('cart_product')
    op.drop_table('product')
    # ### end Alembic commands ###
