"""Updated database

Revision ID: 6817fe0397b6
Revises: ea68d275d873
Create Date: 2023-06-21 06:49:09.797887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6817fe0397b6'
down_revision = 'ea68d275d873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
